import jsPDF from 'jspdf';

// ── Helpers ─────────────────────────────────────────────────────────────────
const fmt = (n: number) =>
    new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 2 }).format(n);

const calcTaxes = (gross: number, isEmployee: boolean) => {
    if (!isEmployee) return { gross, ss: 0, medicare: 0, federal: 0, withholding: 0, net: gross };
    const ss = gross * 0.062;
    const medicare = gross * 0.0145;
    const federal = gross * 0.12;
    const withholding = ss + medicare + federal;
    return { gross, ss, medicare, federal, withholding, net: gross - withholding };
};

const TAX_YEAR = '2025';

// ── Base doc setup ───────────────────────────────────────────────────────────
function baseDoc(churchName: string, ein: string) {
    const doc = new jsPDF({ unit: 'pt', format: 'letter' });
    doc.setFont('helvetica');
    return { doc, churchName: churchName || 'Your Church', ein: ein || 'XX-XXXXXXX' };
}

function drawBox(doc: jsPDF, x: number, y: number, w: number, h: number, label?: string, value?: string, labelSize = 7, valueSize = 10) {
    doc.setDrawColor(180, 180, 180);
    doc.rect(x, y, w, h);
    if (label) {
        doc.setFontSize(labelSize);
        doc.setTextColor(100, 100, 100);
        doc.text(label, x + 4, y + 10);
    }
    if (value) {
        doc.setFontSize(valueSize);
        doc.setTextColor(0, 0, 0);
        doc.text(value, x + 4, y + h - 6);
    }
}

function pageHeader(doc: jsPDF, title: string, subtitle: string, year: string, logoUrl?: string) {
    doc.setFillColor(10, 36, 90);
    doc.rect(0, 0, 612, 52, 'F');
    doc.setFontSize(16);
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 40, 24);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(subtitle, 40, 38);
    
    if (logoUrl && logoUrl.startsWith('data:image')) {
        try {
            // Draw a white circle background for the logo
            doc.setFillColor(255, 255, 255);
            doc.circle(560, 26, 20, 'F');
            doc.addImage(logoUrl, 'PNG', 545, 11, 30, 30);
        } catch (e) {
            console.error('PDF Logo Error:', e);
        }
    }

    doc.setFontSize(12);
    doc.setTextColor(255, 200, 80);
    doc.text(`Tax Year ${year}`, 520, 28, { align: 'right' });
    doc.setTextColor(0, 0, 0);
}

function footer(doc: jsPDF, note: string) {
    doc.setFontSize(7);
    doc.setTextColor(130, 130, 130);
    doc.text(`⚠ This is a worksheet generated by Storehouse Finance. File official IRS forms at irs.gov. ${note}`, 40, 770);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`, 40, 782);
}

// ── W-2 Generator ────────────────────────────────────────────────────────────
export function generateW2(employee: { name: string; role: string; salary: number }, church: { name: string; ein: string; address?: string; logo_url?: string }) {
    const { doc, churchName, ein } = baseDoc(church.name, church.ein);
    const taxes = calcTaxes(employee.salary * 12, true); // Annualize monthly salary
    const addr = church.address || '123 Church Street, City, ST 00000';

    pageHeader(doc, 'Form W-2', 'Wage and Tax Statement', TAX_YEAR, church.logo_url);

    // Employee / Employer boxes
    let y = 65;
    doc.setFontSize(9); doc.setTextColor(30, 30, 30); doc.setFont('helvetica', 'bold');
    doc.text('EMPLOYER INFORMATION', 40, y); doc.setFont('helvetica', 'normal');

    y += 12;
    drawBox(doc, 40, y, 250, 38, 'a  Employer EIN', ein);
    drawBox(doc, 295, y, 270, 38, 'b  Employer Name', churchName);
    y += 44;
    drawBox(doc, 40, y, 525, 30, 'c  Employer Address', addr);

    y += 40;
    doc.setFont('helvetica', 'bold'); doc.setFontSize(9);
    doc.text('EMPLOYEE INFORMATION', 40, y); doc.setFont('helvetica', 'normal');

    y += 12;
    drawBox(doc, 40, y, 250, 38, 'e  Employee Name', employee.name);
    drawBox(doc, 295, y, 270, 38, 'f  Employee Role', employee.role);
    y += 50;

    // Wage Boxes
    doc.setFont('helvetica', 'bold'); doc.setFontSize(9);
    doc.text('WAGE & TAX INFORMATION', 40, y); doc.setFont('helvetica', 'normal');
    y += 12;

    const boxes: [string, string][] = [
        ['1  Wages, Tips, Other Comp', fmt(taxes.gross)],
        ['2  Federal Income Tax Withheld', fmt(taxes.federal)],
        ['3  Social Security Wages', fmt(taxes.gross)],
        ['4  Social Security Tax Withheld', fmt(taxes.ss)],
        ['5  Medicare Wages and Tips', fmt(taxes.gross)],
        ['6  Medicare Tax Withheld', fmt(taxes.medicare)],
        ['12 See Instructions for Box 12', ''],
        ['16 State Wages, Tips, etc.', fmt(taxes.gross)],
        ['17 State Income Tax', fmt(taxes.gross * 0.05)],
        ['18 Local Wages', fmt(taxes.gross)],
    ];

    let col = 0;
    boxes.forEach(([label, value], i) => {
        const x = 40 + (col % 2) * 265;
        if (i > 0 && i % 2 === 0) y += 48;
        drawBox(doc, x, y, 258, 42, label, value);
        col++;
    });

    y += 55;

    // Net summary block
    doc.setFillColor(245, 247, 250);
    doc.rect(40, y, 525, 70, 'F');
    doc.setDrawColor(200, 200, 200);
    doc.rect(40, y, 525, 70);

    doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(10, 36, 90);
    doc.text('ANNUAL COMPENSATION SUMMARY', 52, y + 17);
    doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(40, 40, 40);

    const sumItems = [
        ['Gross Annual Wages:', fmt(taxes.gross)],
        ['Total Withholding:', fmt(taxes.withholding)],
        ['Net Pay (Estimated):', fmt(taxes.net)],
    ];
    sumItems.forEach(([label, val], i) => {
        doc.text(label, 52 + i * 170, y + 38);
        doc.setFont('helvetica', 'bold');
        doc.text(val, 52 + i * 170, y + 52);
        doc.setFont('helvetica', 'normal');
    });

    footer(doc, 'Required by the IRS by Jan 31 each year.');
    doc.save(`W2_${TAX_YEAR}_${employee.name.replace(/\s+/g, '_')}.pdf`);
}

// ── 1099-NEC Generator ───────────────────────────────────────────────────────
export function generate1099NEC(contractor: { name: string; role: string; salary: number }, church: { name: string; ein: string; address?: string; logo_url?: string }) {
    const { doc, churchName, ein } = baseDoc(church.name, church.ein);
    const annual = contractor.salary * 12;
    const addr = church.address || '123 Church Street, City, ST 00000';

    pageHeader(doc, 'Form 1099-NEC', 'Nonemployee Compensation', TAX_YEAR, church.logo_url);

    let y = 70;
    drawBox(doc, 40, y, 525, 35, 'PAYER (Church) — Name, Address, Phone', `${churchName} | ${addr}`);
    y += 42;
    drawBox(doc, 40, y, 260, 32, "PAYER'S EIN", ein);
    drawBox(doc, 305, y, 260, 32, "RECIPIENT'S TIN", 'XXX-XX-XXXX');
    y += 40;
    drawBox(doc, 40, y, 525, 32, "RECIPIENT'S Name", contractor.name);
    y += 40;
    drawBox(doc, 40, y, 525, 32, 'Street Address', '—');
    y += 40;

    doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(10, 36, 90);
    doc.text('COMPENSATION DETAIL', 40, y + 10);
    y += 18;

    const rows = [
        ['Box 1  Nonemployee Compensation', fmt(annual), 'Total paid this tax year'],
        ['Box 4  Federal Tax Withheld', '$0.00', 'Contractors are responsible for self-employment tax'],
        ['Box 5  State Tax Withheld', '$0.00', 'File with state revenue authority as applicable'],
    ];

    rows.forEach(([label, value, note]) => {
        drawBox(doc, 40, y, 525, 44, label, value, 7, 13);
        doc.setFontSize(7); doc.setTextColor(120, 120, 120);
        doc.text(note, 48, y + 38);
        doc.setTextColor(0, 0, 0);
        y += 52;
    });

    // Important note box
    y += 8;
    doc.setFillColor(255, 248, 230);
    doc.rect(40, y, 525, 55, 'F');
    doc.setDrawColor(245, 158, 11);
    doc.rect(40, y, 525, 55);
    doc.setFontSize(8); doc.setTextColor(120, 80, 0);
    doc.setFont('helvetica', 'bold');
    doc.text('⚠  IMPORTANT — Contractor Tax Obligation', 52, y + 14);
    doc.setFont('helvetica', 'normal');
    doc.text(`${contractor.name} is responsible for self-employment tax (15.3%) on compensation exceeding $400.`, 52, y + 27);
    doc.text(`The contractor should file Schedule SE with their Form 1040. This form must be sent by January 31.`, 52, y + 40);

    footer(doc, 'Must be issued to contractor and filed with IRS by Jan 31.');
    doc.save(`1099-NEC_${TAX_YEAR}_${contractor.name.replace(/\s+/g, '_')}.pdf`);
}

// ── Form 941 Generator ───────────────────────────────────────────────────────
export function generate941(staff: any[], church: { name: string; ein: string; logo_url?: string }, quarter: number) {
    const { doc, churchName, ein } = baseDoc(church.name, church.ein);
    const qNames = ['', 'January – March', 'April – June', 'July – September', 'October – December'];

    pageHeader(doc, "Form 941", "Employer's Quarterly Federal Tax Return", TAX_YEAR, church.logo_url);

    let y = 70;
    doc.setFontSize(9); doc.setTextColor(40, 40, 40);
    drawBox(doc, 40, y, 350, 32, 'Employer Name', churchName);
    drawBox(doc, 395, y, 170, 32, 'EIN', ein);
    y += 40;
    drawBox(doc, 40, y, 525, 28, 'Quarter', `Q${quarter} — ${qNames[quarter]} ${TAX_YEAR}`);
    y += 40;

    const employees = staff.filter((s: any) => s.type === 'Full-time' || s.type === 'Part-time');
    const quarterlyGross = employees.reduce((sum: number, s: any) => sum + (s.salary * 3), 0);
    const quarterlyFed = quarterlyGross * 0.12;
    const quarterlySSEmp = quarterlyGross * 0.062;
    const quarterlySSEmr = quarterlyGross * 0.062;
    const quarterlyMedEmp = quarterlyGross * 0.0145;
    const quarterlyMedEmr = quarterlyGross * 0.0145;
    const totalLiability = quarterlyFed + quarterlySSEmp + quarterlySSEmr + quarterlyMedEmp + quarterlyMedEmr;

    const lines: [string, string][] = [
        ['Line 1  — Number of employees who received wages', `${employees.length}`],
        ['Line 2  — Wages, tips, and other compensation', fmt(quarterlyGross)],
        ['Line 3  — Federal income tax withheld from wages', fmt(quarterlyFed)],
        ['Line 5a — Taxable SS wages × 12.4%', fmt(quarterlySSEmp + quarterlySSEmr)],
        ['Line 5c — Taxable Medicare wages × 2.9%', fmt(quarterlyMedEmp + quarterlyMedEmr)],
        ['Line 6  — Total taxes before adjustments', fmt(quarterlyFed + quarterlySSEmp + quarterlySSEmr + quarterlyMedEmp + quarterlyMedEmr)],
        ['Line 12 — Total taxes after adjustments', fmt(totalLiability)],
        ['Line 14 — Balance due', fmt(Math.max(0, totalLiability - quarterlyFed))],
    ];

    lines.forEach(([label, value]) => {
        drawBox(doc, 40, y, 525, 36, label, value);
        y += 42;
    });

    y += 6;
    doc.setFillColor(240, 248, 255);
    doc.rect(40, y, 525, 44, 'F');
    doc.setDrawColor(37, 99, 235);
    doc.rect(40, y, 525, 44);
    doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(10, 36, 90);
    doc.text(`Total Deposit Liability This Quarter:  ${fmt(totalLiability)}`, 52, y + 17);
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(40, 80, 140);
    doc.text(`Due by: ${['', 'April 30', 'July 31', 'October 31', 'January 31'][quarter]}, ${quarter === 4 ? parseInt(TAX_YEAR) + 1 : TAX_YEAR}`, 52, y + 32);

    footer(doc, `Q${quarter} return due by the last day of the month after the quarter ends.`);
    doc.save(`Form941_${TAX_YEAR}_Q${quarter}.pdf`);
}

// ── W-3 Generator ────────────────────────────────────────────────────────────
export function generateW3(staff: any[], church: { name: string; ein: string; logo_url?: string }) {
    const { doc, churchName, ein } = baseDoc(church.name, church.ein);
    const employees = staff.filter((s: any) => s.type === 'Full-time' || s.type === 'Part-time');
    const totals = employees.reduce(
        (acc: any, s: any) => {
            const t = calcTaxes(s.salary * 12, true);
            return {
                gross: acc.gross + t.gross,
                ss: acc.ss + t.ss,
                medicare: acc.medicare + t.medicare,
                federal: acc.federal + t.federal,
            };
        },
        { gross: 0, ss: 0, medicare: 0, federal: 0 }
    );

    pageHeader(doc, 'Form W-3', 'Transmittal of Wage and Tax Statements', TAX_YEAR, church.logo_url);

    let y = 70;
    drawBox(doc, 40, y, 260, 32, 'b  Kind of Payer', 'Church / Religious Organization');
    drawBox(doc, 305, y, 260, 32, 'c  Total number of W-2 forms', `${employees.length}`);
    y += 40;
    drawBox(doc, 40, y, 260, 32, 'Employer EIN', ein);
    drawBox(doc, 305, y, 260, 32, 'Tax Year / Form Type', `${TAX_YEAR} / W-2`);
    y += 40;
    drawBox(doc, 40, y, 525, 32, 'Employer Name & Address', churchName);
    y += 46;

    doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(10, 36, 90);
    doc.text('TOTALS FROM ALL W-2 FORMS', 40, y);
    y += 12;

    const boxes941 = [
        ['1  Wages, Tips, Other Compensation', fmt(totals.gross)],
        ['2  Federal Income Tax Withheld', fmt(totals.federal)],
        ['3  Social Security Wages', fmt(totals.gross)],
        ['4  Social Security Taxes Withheld', fmt(totals.ss)],
        ['5  Medicare Wages', fmt(totals.gross)],
        ['6  Medicare Tax Withheld', fmt(totals.medicare)],
    ];

    let col = 0;
    boxes941.forEach(([label, value], i) => {
        const x = 40 + (col % 2) * 265;
        if (i > 0 && i % 2 === 0) y += 46;
        drawBox(doc, x, y, 258, 40, label, value);
        col++;
    });

    y += 58;
    doc.setFillColor(240, 250, 245);
    doc.rect(40, y, 525, 55, 'F');
    doc.setDrawColor(16, 185, 129);
    doc.rect(40, y, 525, 55);
    doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(8, 90, 50);
    doc.text('SUMMARY', 52, y + 17);
    doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(20, 60, 30);
    doc.text(`Total employees: ${employees.length}   |   Total gross wages: ${fmt(totals.gross)}   |   Total withheld: ${fmt(totals.federal + totals.ss + totals.medicare)}`, 52, y + 34);

    footer(doc, 'W-3 must accompany all W-2 copies to SSA by January 31.');
    doc.save(`Form_W3_${TAX_YEAR}.pdf`);
}

// ── Form 990 Summary ─────────────────────────────────────────────────────────
export function generate990Summary(totals: { income: number; expenses: number; balance: number; members: number }, church: { name: string; ein: string; logo_url?: string }) {
    const { doc, churchName, ein } = baseDoc(church.name, church.ein);

    pageHeader(doc, 'Form 990 — Summary Worksheet', 'Return of Organization Exempt From Income Tax (Nonprofit)', TAX_YEAR, church.logo_url);

    let y = 70;
    drawBox(doc, 40, y, 350, 32, 'Organization Name', churchName);
    drawBox(doc, 395, y, 170, 32, 'EIN', ein);
    y += 40;
    drawBox(doc, 40, y, 525, 28, 'Tax Year', `January 1, ${TAX_YEAR} — December 31, ${TAX_YEAR}`);
    y += 38;
    drawBox(doc, 40, y, 525, 28, 'Organization Type', '501(c)(3) — Religious Organization');
    y += 42;

    doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(10, 36, 90);
    doc.text('PART I — REVENUE, EXPENSES & CHANGES IN NET ASSETS', 40, y);
    y += 14;

    const netAssets = totals.income - totals.expenses;
    const lines990: [string, string][] = [
        ['Line 1   Total contributions (tithes, offerings, donations)', fmt(totals.income)],
        ['Line 8   Total Revenue', fmt(totals.income)],
        ['Line 13  Grants and similar amounts paid', '$0.00'],
        ['Line 16  Salaries, compensation, other employee benefits', fmt(totals.expenses * 0.7)],
        ['Line 17  Other expenses (facilities, programs, outreach)', fmt(totals.expenses * 0.3)],
        ['Line 18  Total Expenses', fmt(totals.expenses)],
        ['Line 19  Revenue Less Expenses', fmt(netAssets)],
        ['Line 22  Net Assets at End of Year', fmt(totals.balance)],
    ];

    lines990.forEach(([label, value]) => {
        const isExpense = label.includes('16') || label.includes('17') || label.includes('18');
        const isNet = label.includes('19') || label.includes('22');
        if (isExpense) { doc.setTextColor(180, 40, 40); }
        else if (isNet) { doc.setTextColor(10, 90, 40); }
        else { doc.setTextColor(0, 0, 0); }
        drawBox(doc, 40, y, 525, 36, label, value);
        doc.setTextColor(0, 0, 0);
        y += 42;
    });

    y += 6;
    doc.setFillColor(248, 250, 255);
    doc.rect(40, y, 525, 48, 'F');
    doc.setDrawColor(100, 100, 200);
    doc.rect(40, y, 525, 48);
    doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(30, 30, 90);
    doc.text('PART V — STATEMENTS REGARDING OTHER IRS FILINGS', 52, y + 14);
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(60, 60, 100);
    doc.text(`Number of W-2s issued: See payroll records   |   Forms 1099-NEC filed: See contractor records   |   Members: ${totals.members}`, 52, y + 30);

    footer(doc, 'Complete Form 990 or 990-EZ at irs.gov by May 15. This worksheet helps prepare your return.');
    doc.save(`Form990_Summary_${TAX_YEAR}.pdf`);
}
