import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    dashboard: 'Dashboard',
    members: 'Members',
    accounting: 'Accounting',
    expenses: 'Expenses',
    reports: 'Reports',
    budget: 'Budget',
    settings: 'Settings',
    projection: 'Neural Projection',
    missionMatrix: 'Mission Matrix',
    nextMonthRevenue: "Next month's revenue is projected to be",
    trackNew: 'Track New Initiative',
    searchPlaceholder: 'Search apps, members, or commands...',
    querying: 'Querying Neural Index...',
    profilesFound: 'Profiles Found',
    financialFunds: 'Financial Funds',
    transactions: 'Transactions',
    noResults: 'No results found in Neural Index',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    actions: 'Actions',
    status: 'Status',
    date: 'Date',
    amount: 'Amount',
    description: 'Description',
    category: 'Category',
    department: 'Department',
    total: 'Total',
    loading: 'Loading...',
    success: 'Success',
    error: 'Error',
    syncing: 'Syncing...',
    saveToCloud: 'Save to Cloud',
    planNextYear: 'Plan Next Year',
    fiscalYear: 'Fiscal Year',
    annualLimit: 'Annual Budget Limit',
    allocationWeight: 'Allocation Weight',
    verified: 'Verified',
    overBudget: 'Over Budget',
    auditLog: 'Strategic Audit Log',
    revenue: 'Revenue',
    donations: 'Donations',
    tithes: 'Tithes',
    offerings: 'Offerings',
    totalBalance: 'Total Balance',
    monthlyGrowth: 'Monthly Growth',
    activeCongregation: 'Active Congregation',
    expenditure: 'Expenditure',
    intelligence: 'Neural Intelligence',
    strategicGoals: 'Strategic Goals',
    recentActivity: 'Recent Activity',
    viewAll: 'View All',
    neuralAlerts: 'Neural Alerts',
    predictedRevenue: 'Predicted Revenue',
    confidenceScore: 'Confidence Score',
    smartGiving: 'Smart Giving',
    automatedPayroll: 'Automated Payroll',
    globalReports: 'Global Reports',
    financialIntegrity: 'Financial Integrity',
    scanReceipt: 'Scan Receipt',
    useCamera: 'Use Camera',
    uploadReceipt: 'Upload Receipt',
    processing: 'Processing Neural Vision...',
    expenseSubmission: 'Expense Submission',
    paymentMethod: 'Payment Method',
    allCategories: 'All Categories',
    allDepartments: 'All Departments',
    filterByDate: 'Filter by Date',
    addExpense: 'Add New Expense',
    editExpense: 'Edit Expense',
    viewReceipt: 'View Receipt',
    noReceipt: 'No Receipt Attached',
    confirmDelete: 'Are you sure you want to delete this?',
    rapidNavigation: 'Rapid Navigation',
    goToDashboard: 'Go to Dashboard',
    searchMembers: 'Search Members',
    fiscalPlanning: 'Fiscal Planning',
    fundAccounting: 'Fund Accounting',
    trialEnding: 'Trial ending in',
    days: 'days',
    day: 'day',
    upgradeNow: 'Upgrade Now',
    renewsIn: 'Subscription renews in',
    activeTrial: 'Free trial',
    remaining: 'remaining',
    seePlans: 'See Plans',
    loadingWorkspace: 'Loading your workspace...',
    congregation: 'Congregation',
    activeMembers: 'Active Members',
    addMember: 'Add Member',
    editMember: 'Edit Member',
    sendStatement: 'Send Statement',
    viewStatement: 'View Statement',
    joined: 'Joined',
    role: 'Role',
    volunteer: 'Volunteer',
    deacon: 'Deacon',
    member: 'Member',
    boardReport: 'Monthly Board Report',
    pnlStatement: 'Profit & Loss Statement',
    balanceSheet: 'Balance Sheet',
    cashflowStatement: 'Cashflow Statement',
    executive: 'Executive',
    financial: 'Financial',
    month0: 'January',
    month1: 'February',
    month2: 'March',
    month3: 'April',
    month4: 'May',
    month5: 'June',
    month6: 'July',
    month7: 'August',
    month8: 'September',
    month9: 'October',
    month10: 'November',
    month11: 'December'
  },
  es: {
    dashboard: 'Panel de Control',
    members: 'Miembros',
    accounting: 'Contabilidad',
    expenses: 'Gastos',
    reports: 'Informes',
    budget: 'Presupuesto',
    settings: 'Ajustes',
    projection: 'Proyección Neuronal',
    missionMatrix: 'Matriz de Misión',
    nextMonthRevenue: 'Se proyecta que los ingresos del próximo mes serán',
    trackNew: 'Rastrear Nueva Iniciativa',
    searchPlaceholder: 'Busque aplicaciones, miembros o comandos...',
    querying: 'Consultando Índice Neuronal...',
    profilesFound: 'Perfiles Encontrados',
    financialFunds: 'Fondos Financieros',
    transactions: 'Transacciones',
    noResults: 'No se encontraron resultados en el Índice Neuronal',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    actions: 'Acciones',
    status: 'Estado',
    date: 'Fecha',
    amount: 'Monto',
    description: 'Descripción',
    category: 'Categoría',
    department: 'Departamento',
    total: 'Total',
    loading: 'Cargando...',
    success: 'Éxito',
    error: 'Error',
    syncing: 'Sincronizando...',
    saveToCloud: 'Guardar en la Nube',
    planNextYear: 'Planear Próximo Año',
    fiscalYear: 'Año Fiscal',
    annualLimit: 'Límite Presupuestario Anual',
    allocationWeight: 'Peso de Asignación',
    verified: 'Verificado',
    overBudget: 'Excedido',
    auditLog: 'Registro de Auditoría Estratégica',
    revenue: 'Ingresos',
    donations: 'Donaciones',
    tithes: 'Diezmos',
    offerings: 'Ofrendas',
    totalBalance: 'Saldo Total',
    monthlyGrowth: 'Crecimiento Mensual',
    activeCongregation: 'Congregación Activa',
    expenditure: 'Gastos Totales',
    intelligence: 'Inteligencia Neuronal',
    strategicGoals: 'Metas Estratégicas',
    recentActivity: 'Actividad Reciente',
    viewAll: 'Ver Todo',
    neuralAlerts: 'Alertas Neuronales',
    predictedRevenue: 'Ingresos Predichos',
    confidenceScore: 'Nivel de Confianza',
    smartGiving: 'Donación Inteligente',
    automatedPayroll: 'Nómina Automatizada',
    globalReports: 'Informes Globales',
    financialIntegrity: 'Integridad Financiera',
    scanReceipt: 'Escanear Recibo',
    useCamera: 'Usar Cámara',
    uploadReceipt: 'Subir Recibo',
    processing: 'Procesando Visión Neuronal...',
    expenseSubmission: 'Envío de Gasto',
    paymentMethod: 'Método de Pago',
    allCategories: 'Todas las Categorías',
    allDepartments: 'Todos los Departamentos',
    filterByDate: 'Filtrar por Fecha',
    addExpense: 'Agregar Nuevo Gasto',
    editExpense: 'Editar Gasto',
    viewReceipt: 'Ver Recibo',
    noReceipt: 'Sin Recibo Adjunto',
    confirmDelete: '¿Está seguro de que desea eliminar esto?',
    rapidNavigation: 'Navegación Rápida',
    goToDashboard: 'Ir al Panel',
    searchMembers: 'Buscar Miembros',
    fiscalPlanning: 'Planificación Fiscal',
    fundAccounting: 'Contabilidad de Fondos',
    trialEnding: 'La prueba termina en',
    days: 'días',
    day: 'día',
    upgradeNow: 'Actualizar Ahora',
    renewsIn: 'La suscripción se renueva en',
    activeTrial: 'Prueba gratuita',
    remaining: 'restantes',
    seePlans: 'Ver Planes',
    loadingWorkspace: 'Cargando su espacio de trabajo...',
    congregation: 'Congregación',
    activeMembers: 'Miembros Activos',
    addMember: 'Agregar Miembro',
    editMember: 'Editar Miembro',
    sendStatement: 'Enviar Estado',
    viewStatement: 'Ver Estado',
    joined: 'Se unió',
    role: 'Rol',
    volunteer: 'Voluntario',
    deacon: 'Diácono',
    member: 'Miembro',
    boardReport: 'Informe de la Junta Mensual',
    pnlStatement: 'Estado de Pérdidas y Ganancias',
    balanceSheet: 'Balance General',
    cashflowStatement: 'Estado de Flujo de Caja',
    executive: 'Ejecutivo',
    financial: 'Financiero',
    month0: 'Enero',
    month1: 'Febrero',
    month2: 'Marzo',
    month3: 'Abril',
    month4: 'Mayo',
    month5: 'Junio',
    month6: 'Julio',
    month7: 'Agosto',
    month8: 'Septiembre',
    month9: 'Octubre',
    month10: 'Noviembre',
    month11: 'Diciembre'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => 
    (localStorage.getItem('language') as Language) || 'en'
  );

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string) => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
