import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    dashboard: 'Dashboard',
    members: 'Members',
    accounting: 'Accounting',
    expenses: 'Expenses',
    reports: 'Reports',
    budget: 'Budget',
    settings: 'Settings',
    projection: 'Neural Projection',
    missionMatrix: 'Mission Matrix',
    nextMonthRevenue: 'Next month revenue is projected at',
    trackNew: 'Track New Initiative',
    searchPlaceholder: 'Search apps, members, or commands (Ctrl+K)...',
    querying: 'Querying Neural Index...',
    profilesFound: 'Profiles Found',
    financialFunds: 'Financial Funds',
    transactions: 'Transactions',
    noResults: 'No results found in Neural Index',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    actions: 'Actions',
    status: 'Status',
    date: 'Date',
    amount: 'Amount',
    description: 'Description',
    category: 'Category',
    department: 'Department',
    total: 'Total',
    loading: 'Loading...',
    success: 'Success',
    error: 'Error',
    syncing: 'Syncing...',
    saveToCloud: 'Save to Cloud',
    planNextYear: 'Plan Next Year',
    fiscalYear: 'Fiscal Year',
    annualLimit: 'Annual Budget Ceiling',
    allocationWeight: 'Allocation Weight',
    verified: 'Verified',
    overBudget: 'Over Budget',
    auditLog: 'Strategic Audit Log',
    revenue: 'Revenue',
    donations: 'Donations',
    tithes: 'Tithes',
    offerings: 'Offerings',
    totalBalance: 'Total Balance',
    monthlyGrowth: 'Monthly Growth',
    activeCongregation: 'Active Congregation',
    expenditure: 'Total Expenditures',
    intelligence: 'Neural Intelligence',
    strategicGoals: 'Strategic Goals',
    recentActivity: 'Recent Activity',
    viewAll: 'View All',
    neuralAlerts: 'Neural Alerts',
    predictedRevenue: 'Predicted Revenue',
    confidenceScore: 'Confidence Score',
    smartGiving: 'Smart Giving',
    automatedPayroll: 'Automated Payroll',
    globalReports: 'Global Reports',
    financialIntegrity: 'Financial Integrity',
    scanReceipt: 'Scan Receipt',
    useCamera: 'Use Camera',
    uploadReceipt: 'Upload Receipt',
    processing: 'Processing Neural Vision...',
    expenseSubmission: 'Expense Submission',
    paymentMethod: 'Payment Method',
    allCategories: 'All Categories',
    allDepartments: 'All Departments',
    filterByDate: 'Filter by Date',
    addExpense: 'Add New Expense',
    editExpense: 'Edit Expense',
    viewReceipt: 'View Receipt',
    noReceipt: 'No Receipt Attached',
    confirmDelete: 'Are you sure you want to delete this?',
    rapidNavigation: 'Rapid Navigation',
    goToDashboard: 'Go to Dashboard',
    searchMembers: 'Search Members',
    fiscalPlanning: 'Fiscal Planning',
    fundAccounting: 'Fund Accounting',
    trialEnding: 'Trial ending in',
    days: 'days',
    day: 'day',
    upgradeNow: 'Upgrade Now',
    renewsIn: 'Renews in',
    activeTrial: 'Active Trial',
    remaining: 'remaining',
    seePlans: 'See Plans',
    loadingWorkspace: 'Loading your workspace...',
    congregation: 'Congregation',
    activeMembers: 'Active Members',
    addMember: 'Add Member',
    editMember: 'Edit Member',
    sendStatement: 'Send Statement',
    viewStatement: 'View Statement',
    joined: 'Joined',
    role: 'Role',
    volunteer: 'Volunteer',
    deacon: 'Deacon',
    financialOverview: 'Financial Overview',
    revenueVsExpenses: 'Revenue vs Expenses',
    newTransaction: 'New Transaction',
    exportPDF: 'Export PDF',
    recentTransactions: 'Recent Transactions',
    financialHealth: 'Financial Health',
    quickAccess: 'Quick Access',
    missionMatrixDesc: 'Real-time fund progression',
    latestLedgerActivity: 'Latest ledger activity',
    keyPerformanceIndicators: 'Key Performance Indicators',
    budgetUtilization: 'Budget Utilization',
    withinTarget: 'Within target',
    nearLimit: 'Near limit',
    secureEncrypted: 'Secure & Encrypted',
    dataProtected: 'All data protected',
    analyticsTitle: 'Financial Analytics',
    analyticsDesc: 'YTD/MTD metrics, revenue trends, and expense breakdowns.',
    memberMgmtTitle: 'Member Management',
    memberMgmtDesc: 'Secure database with full giving history and insights.',
    expenseWorkflowTitle: 'Expense Workflow',
    expenseWorkflowDesc: 'Categorized expense tracking with multi-level approvals.',
    smartGivingDesc: 'Online giving, pledge tracking, and donor analytics.',
    payrollStaffTitle: 'Payroll & Staff',
    payrollStaffDesc: 'Automated payroll with tax calculations and compliance.',
    budgetPlanningTitle: 'Budget Planning',
    budgetPlanningDesc: 'Annual budget allocation by department and fund.',
    live: 'Live',
    thisMonth: 'This month',
    unusualPatternsDetected: 'Unusual Patterns Detected',
    neuralEngineFlagged: 'Our neural engine identified transactions deviating significantly from your 6-month average.',
    strategic: 'Strategic',
    fiscalManagementDesc: 'Multi-year fiscal management and resource planning',
    defineCeiling: 'Define the total ceiling for this fiscal period',
    addAllocationLine: 'ADD NEW ALLOCATION LINE',
    selectDepartment: 'Select a department...',
    allocationIntegrity: 'Allocation Integrity',
    systemBalanced: 'System Balanced',
    imbalance: 'Imbalance',
    totalPledgesBudget: 'Total Budget/Pledges',
    historicalContext: 'Historical Context',
    viewingBudgetFor: 'Viewing budget for ',
    planningFutureYears: '. Planning for future years allows the church to anticipate growth.',
    expenseRegistry: 'Expense Registry',
    auditableRecordDesc: 'Auditable record of disbursements',
    new: 'New',
    clear: 'Clear',
    savePreset: 'Save Preset',
    outflowTotal: 'Outflow Total',
    updateExpense: 'Update Expense',
    newExpense: 'New Expense',
    receiptPdf: 'Receipt Image or PDF',
    uploadDoc: 'Upload Doc',
    uploadingSecureDoc: 'Uploading secure document...',
    pdfUploaded: 'PDF Uploaded',
    recordUpdate: 'Record Update',
    commitToLedger: 'Commit to Ledger',
    useCameraApp: 'Use Camera App',
    browseFiles: 'Browse Files',
    extractingLineItems: 'Extracting line items with AI...',
    receiptExtracted: 'Receipt Extracted',
    confirmDetailsDesc: 'Please confirm the details before saving.',
    churchDepartments: 'Church Departments',
    departmentsDesc: 'Manage and organize your various ministries and operational units.',
    createDepartment: 'Create Department',
    editDepartment: 'Edit Department',
    newDepartment: 'New Department',
    updateDetailsDesc: 'Update details for this department.',
    initializeMinistryDesc: 'Initialize a new ministry or functional department.',
    departmentName: 'DEPARTMENT NAME',
    departmentHead: 'DEPARTMENT HEAD',
    classification: 'CLASSIFICATION',
    briefPurposeDesc: 'Brief purpose of the department...',
    membersVolunteers: 'Members / Volunteers',
    viewRoster: 'View Roster',
    communityCore: 'Community Core',
    cultivatingEngagementDesc: 'Cultivating engagement and nurturing spiritual growth',
    bulkStatements: 'Bulk Statements',
    membersUsed: 'members used',
    statement: 'Statement',
    editMemberDetails: 'Edit Member Details',
    removeMember: 'Remove Member',
    manuallyAddMemberDesc: 'Manually add a member to the database.',
    churchTreasurer: 'Church Treasurer',
    preparedFor: 'PREPARED FOR',
    totalContributed: 'TOTAL CONTRIBUTED',
    statementPeriod: 'Statement Period',
    statementDate: 'Statement Date',
    contributionStatement: 'CONTRIBUTION STATEMENT',
    updateDetailsFor: 'Update details for',
    boardReport: 'Monthly Board Report',
    pnlStatement: 'Profit & Loss Statement',
    balanceSheet: 'Balance Sheet',
    cashflowStatement: 'Cash Flow Statement',
    financialIntelligence: 'Financial Intelligence',
    auditReadyDesc: 'Audit-ready financial statements, board-ready insights, and real-time stewardship tracking.',
    missionCriticalStatements: 'Mission Critical Statements',
    viewNow: 'View Now',
    automatedReports: 'Automated Reports',
    monthlyFinancialClose: 'Monthly Financial Close',
    nextRun: 'Next run',
    activeSchedule: 'Active Schedule',
    manageRecipients: 'Manage Recipients',
    revenueAccuracy: 'Revenue Accuracy',
    boardCompliance: 'Board Compliance',
    auditTrail: 'Audit Trail',
    reportLatency: 'Report Latency',
    newAuditRequest: 'New Audit Request',
    statementOfActivity: 'Statement of Activity',
    operatingPeriod: 'Operating Period',
    netOperatingIncome: 'Net Operating Income',
    revenueSources: 'Revenue Sources',
    operatingExpenses: 'Operating Expenses',
    totalExpenditures: 'Total Expenditures',
    statementOfFinancialPosition: 'Statement of Financial Position',
    reportingDate: 'Reporting Date',
    consolidatedAssets: 'Consolidated Assets',
    cashLiquidEquivalents: 'Cash & Liquid Equivalents',
    totalPortfolioValue: 'Total Portfolio Value',
    netAssetsEquity: 'Net Assets (Equity)',
    designatedRestrictedFunds: 'Designated/Restricted Funds',
    operatingGeneralFunds: 'Operating/General Funds',
    totalEquity: 'Total Equity',
    assetIntegrityVerified: 'Asset Integrity Verified',
    ledgerBalancesMatchDesc: 'Ledger balances match historical fund allocations accurately.',
    boardPerformanceSummary: 'Board Performance Summary',
    financialHealthStewardshipOverview: 'Financial Health & Stewardship Overview',
    totalMonthlyRevenue: 'Total Monthly Revenue',
    administrativeOutflow: 'Administrative Outflow',
    missionSurplus: 'Mission Surplus',
    revenueInflow: 'Revenue Inflow',
    categorizedStewardshipDesc: 'Categorized stewardship by department and fund type',
    operationalOutflow: 'Operational Outflow',
    topMonthlyExpenditureDesc: 'Top monthly expenditure categories',
    monthlyTotal: 'MONTHLY TOTAL',
    revenueBySource: 'Revenue by Source',
    expenseAllocation: 'Expense Allocation',
    totalDesignatedRevenue: 'Total Designated Revenue',
    totalStewardshipBurn: 'Total Stewardship Burn',
    analyzingChurchFinances: 'Analyzing Church Finances...',
    publishToBoard: 'Publish to Board',
    tracingMovementDesc: 'Tracing the movement of liquid assets across operating cycles.',
    operatingInflow: 'Operating Inflow',
    operatingOutflow: 'Operating Outflow',
    executive: 'Executive',
    financial: 'Financial',
    month0: 'January',
    month1: 'February',
    month2: 'March',
    month3: 'April',
    month4: 'May',
    month5: 'June',
    month6: 'July',
    month7: 'August',
    month8: 'September',
    month9: 'October',
    month10: 'November',
    month11: 'December',
    // Settings
    systemConfiguration: 'System Configuration',
    workspaceSettings: 'Workspace Settings',
    manageOrgDetails: "Manage your organization's core details, billing, and team permissions.",
    churchIdentity: 'Church Identity',
    churchIdentityDesc: 'Name, logo, address and contact information.',
    financialControls: 'Financial Controls',
    financialControlsDesc: 'Currency, fiscal year, and tax configuration.',
    billing: 'Plans & Billing',
    billingDesc: 'Subscription details and payment methods.',
    security: 'Security & Team',
    securityDesc: 'Admin permissions and multi-factor auth.',
    appearance: 'Appearance',
    appearanceDesc: 'Theme, brand colors, and display density.',
    notifications: 'Notifications',
    notificationsDesc: 'Email alerts for budgets and expenses.',
    configure: 'Configure',
    saveChanges: 'Save Changes',
    backToSettings: 'Back to Settings',
    manageChurchAppearance: 'Manage how your church appears across the platform and reports.',
    churchName: 'Church Name',
    website: 'Website',
    taxIdEin: 'Tax ID / EIN',
    physicalAddress: 'Physical Address',
    verifiedStatus: 'Verified Status',
    verifiedStatusDesc: 'Your church profile is currently verified for tax-compliant receipting.',
    adminAccess: 'Administrative Access',
    primaryAdmin: 'Primary Admin',
    inviteTeamMember: 'Invite Team Member',
    securityProtocols: 'Security Protocols',
    mfa: 'Multi-Factor Authentication',
    mfaDesc: 'Require 2FA for all administrator logins.',
    usageHistory: 'Usage History',
    viewAllInvoices: 'View all invoices',
    planLimits: 'Plan Limits',
    themeMode: 'Theme Mode',
    brandColor: 'Brand Color',
    displayDensity: 'Display Density',
    emailAlerts: 'Email Alerts',
    systemAnnouncements: 'System Announcements',
    fiscalSettings: 'Configure your currency, fiscal settings, and tax compliance parameters.',
    regionalCurrency: 'Regional & Currency',
    baseCurrency: 'Base Currency',
    fiscalYearStart: 'Fiscal Year Start',
    taxCompliance: 'Tax Compliance',
    taxExemptStatus: 'Tax-Exempt Status',
    taxExemptDesc: 'Apply 501(c)(3) or charitable status to all financial reports.',
    autoTaxReceipts: 'Automated Tax Receipts',
    autoTaxReceiptsDesc: 'Send annual tax documentation to all donors automatically.',
    subscriptionExpired: 'Subscription Expired',
    trialEndedDesc: 'Your trial has ended. Please upgrade to a paid plan to regain full access to all features.',
    currentPlan: 'Current Plan',
    freeTrialEndsIn: 'Free trial ends in',
    daysWithDate: 'days',
    subscriptionActiveRenews: 'Subscription active — Renews on',
    upgradePlan: 'Upgrade Plan',
    connectedDefault: 'Connected (Default)',
    viewAllInvoicesArrow: 'View all invoices →',
    memberLimit: 'Member Limit',
    unlimited: 'Unlimited',
    membersUsageDesc: 'You are currently using {used} of {total} allowed members.',
    backToBilling: 'Back to Billing',
    congratulationsUpgrade: 'Congratulations! Your church has been upgraded successfully.',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    compact: 'Compact',
    spacious: 'Spacious',
    budgetThresholds: 'Budget Thresholds',
    budgetThresholdsDesc: 'Notify when a department exceeds 80% of its monthly budget.',
    payrollReminders: 'Payroll Reminders',
    payrollRemindersDesc: 'Receive alerts 2 days before scheduled payroll processing.',
    securityEvents: 'Security Events',
    securityEventsDesc: 'Alert for new admin logins or permission changes.',
    givingReports: 'Giving Reports',
    givingReportsDesc: 'Weekly summary of tithes and smart giving activity.',
    receiveFeatureUpdates: 'Receive updates about new platform features and maintenance.',
    // Payroll
    teamCompensation: 'Team Compensation',
    payrollDesc: 'Automated payroll management for church staff and specialized contractors',
    taxCenter: 'Tax Center',
    runPayroll: 'Run Payroll',
    onboardStaff: 'Onboard Staff',
    hireNewStaff: 'Hire New Staff',
    hireStaffDesc: 'Add a new employee or contractor to payroll.',
    fullName: 'Full Name',
    positionRole: 'Position Role',
    type: 'Type',
    salaryRate: 'Salary / Rate',
    payFrequency: 'Pay Frequency',
    setRecurring: 'Set as Recurring Payment',
    payrollSuccessful: 'Payroll Successful',
    totalDisbursed: 'Total Amount Disbursed',
    nextPayrollRun: 'Next Payroll Run',
    activeWorkforce: 'Active Workforce',
    actionRequired: 'Action Required',
    staffRegistry: 'Staff Registry',
    grossSalary: 'Gross Salary',
    netDisbursement: 'Net Disbursement',
    financialCompliance: 'Financial Compliance',
    complianceDesc: 'Secure tax handling, automated filings, and audit-ready reporting',
    auditShield: 'Audit Shield',
    // Fund Accounting
    fundStewardship: 'Fund Stewardship',
    fundStewardshipDesc: 'Full visibility into Tithes, Restricted Offerings, and Global Missions',
    reconcileBank: 'Reconcile Bank',
    recordDeposit: 'Record Deposit',
    integratedLedger: 'Integrated Ledger',
    ledgerDesc: 'Unified view of all departmental and fund activities',
    bankReconHub: 'Bank Reconciliation Hub',
    bankStatementItems: 'Bank Statement Items',
    ledgerRecommendations: 'Ledger Recommendations',
    plansPricing: 'Plans & Pricing',
    departments: 'Departments',
    allocationDetails: 'Allocation Details',
    destinationFund: 'Destination Fund',
    bankReconDesc: 'Auto-matching transactions from Chase Operating Account (...4920)',
    refreshFeed: 'Refresh Feed',
    processMatches: 'Process All Matches',
    suggestedMatch: 'Suggested Match Found',
    exactMatchDesc: 'Entry "{desc}" dated {date} matches exactly.',
    confirmMatch: 'Confirm Match',
    noDirectMatch: 'No direct matches for {desc}.',
    createLedgerLink: 'Create Ledger Link',
    accountStatus: 'Account Status',
    contributor: 'Contributor',
    typeToSearch: 'Type to search member...',
    departmentAllocations: 'Department Allocations',
    closeAuditView: 'Close Audit View',
    history: 'History',
    autoMatchedLedger: 'Auto-Matched to Ledger',
    // Fund Names/Types
    generalFundTithes: 'General Fund (Tithes)',
    buildingCampaign: 'Building Campaign',
    missionsOutreach: 'Missions & Outreach',
    youthMinistry: 'Youth Ministry',
    operational: 'Operational',
    restricted: 'Restricted',
    purpose: 'Purpose',
    active: 'Active',
    low: 'Low',
    healthy: 'Healthy',
    // New Payroll Keys
    amShift: 'AM Shift',
    pmShift: 'PM Shift',
    tMinus8Days: 'T-Minus 8 Days',
    estDisbursement: 'Est. Disbursement',
    allCompliant: 'All Compliant',
    pendingApproval: 'Pending Approval',
    invoiceVerificationNeeded: 'Invoice verification needed',
    staffRegistryDesc: 'Centralized management of team structure and compensation',
    searchDirectory: 'Search directory...',
    exportData: 'Export Data',
    morning: 'Morning',
    evening: 'Evening',
    shift: 'Shift',
    today: 'Today',
    contractors: 'contractors',
    done: 'Done',
    payroll: 'Payroll',
    logout: 'Logout',
    notes: 'Notes',
    weighted: 'weighted',
    statementDear: 'Dear',
    statementGratitude: 'We hope this letter finds you well. On behalf of {churchName}, we would like to express our sincere gratitude for your continued support and faithful stewardship.',
    statementAttached: 'Attached or listed below is your financial contribution statement for {month} {year}.',
    statementTotalContribution: 'Total Monthly Contribution',
    statementTransactionRecord: 'TRANSACTION RECORD',
    statementQuestions: 'Your contributions allow us to continue the work of the ministry and serve our community effectively. If you have any questions regarding this statement, please do not hesitate to contact the finance office.',
    statementBlessings: 'Blessings',
    statementTreasurerLabel: 'Treasurer',
    statementOfficialReceipt: 'This statement serves as an official receipt for your contributions to {churchName} for the period of {month} {year}. Your faithful support empowers our ministries and community initiatives. We thank you for your ongoing partnership in our mission.',
    statementOfficialSubject: 'Official Contribution Statement',
    dateLabel: 'Date',
    fundAllocation: 'Fund Allocation',
    churchMessage: 'A Message from Your Church',
    stewardshipMessage: 'Dear {name}, thank you for your faithful stewardship this month. Your contribution of {amount} helps us continue our mission of providing spiritual nourishment and community outreach. Your generosity empowers our ministries and transforms lives through faith.',
    financeTeam: 'Finance Team',
    stewardshipCertification: 'Official Stewardship Certification',
    donorInformation: 'Donor Information',
    memberSince: 'Member since',
    transactionDetails: 'Transaction Details',
    noDonationsRecorded: 'No donations recorded for this period.',
    treasurerSignatureName: 'Treasurer Signature Name',
    print: 'Print',
    sendToMember: 'Send to Member',
    emailSent: 'Email Sent!',
    operatingExp: 'Operating Exp',
    restrictedExp: 'Restricted Exp',
    purposeExp: 'Purpose Exp',
    buildingFacilities: 'Building & Facilities',
    tithesFinance: 'Tithes & Finance',
    sabbathSchool: 'Sabbath School',
    sundaySchool: 'Sunday School',
    cash: 'Cash',
    check: 'Check',
    online: 'Online',
    mobileApp: 'Mobile App',
    optionalNotesLabel: 'Optional notes about this transaction',
    recordedManually: 'Recorded manually via Fund Stewardship portal. Method: {method}',
    importedGateway: 'Imported from Online Gateway',
    seniorPastor: 'Senior Pastor',
    worshipDirector: 'Worship Director',
    youthPastor: 'Youth Pastor',
    cleaner: 'Cleaner',
    itSupport: 'IT Support',
    securityDetail: 'Security Detail',
    fullTime: 'Full-time',
    contractor: 'Contractor',
    paid: 'Paid',
    pending: 'Pending',
    monthly: 'Monthly',
    twiceDaily: 'Twice Daily',
    'Senior Pastor': 'Senior Pastor',
    'Worship Director': 'Worship Director',
    'Youth Pastor': 'Youth Pastor',
    'Cleaner': 'Cleaner',
    'IT Support': 'IT Support',
    'Security Detail': 'Security Detail',
    'Full-time': 'Full-time',
    'Part-time': 'Part-time',
    'Contractor': 'Contractor',
    'Paid': 'Paid',
    'Pending': 'Pending',
    'Monthly': 'Monthly',
    'Twice Daily': 'Twice Daily',
    'Weekly': 'Weekly',
  },
  es: {
    dashboard: 'Panel de Control',
    members: 'Miembros',
    accounting: 'Contabilidad',
    expenses: 'Gastos',
    reports: 'Informes',
    budget: 'Presupuesto',
    settings: 'Ajustes',
    projection: 'Proyección Neuronal',
    missionMatrix: 'Matriz de Misión',
    nextMonthRevenue: 'Se proyecta que los ingresos del próximo mes serán',
    trackNew: 'Rastrear Nueva Iniciativa',
    searchPlaceholder: 'Busque aplicaciones, miembros o comandos (Ctrl+K)...',
    querying: 'Consultando Índice Neuronal...',
    profilesFound: 'Perfiles Encontrados',
    financialFunds: 'Fondos Financieros',
    transactions: 'Transacciones',
    noResults: 'No se encontraron resultados en el Índice Neuronal',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    actions: 'Acciones',
    status: 'Estado',
    date: 'Fecha',
    amount: 'Monto',
    description: 'Descripción',
    category: 'Categoría',
    department: 'Departamento',
    total: 'Total',
    loading: 'Cargando...',
    success: 'Éxito',
    error: 'Error',
    syncing: 'Sincronizando...',
    saveToCloud: 'Guardar en la Nube',
    planNextYear: 'Planear Próximo Año',
    fiscalYear: 'Año Fiscal',
    annualLimit: 'Límite Presupuestario Anual',
    allocationWeight: 'Peso de Asignación',
    verified: 'Verificado',
    overBudget: 'Excedido',
    auditLog: 'Registro de Auditoría Estratégica',
    revenue: 'Ingresos',
    donations: 'Donaciones',
    tithes: 'Diezmos',
    offerings: 'Ofrendas',
    totalBalance: 'Saldo Total',
    monthlyGrowth: 'Crecimiento Mensual',
    activeCongregation: 'Congregación Activa',
    expenditure: 'Gastos Totales',
    intelligence: 'Inteligencia Neuronal',
    strategicGoals: 'Metas Estratégicas',
    recentActivity: 'Actividad Reciente',
    viewAll: 'Ver Todo',
    neuralAlerts: 'Alertas Neuronales',
    predictedRevenue: 'Ingresos Predichos',
    confidenceScore: 'Nivel de Confianza',
    smartGiving: 'Donación Inteligente',
    automatedPayroll: 'Nómina Automatizada',
    globalReports: 'Informes Globales',
    financialIntegrity: 'Integridad Financiera',
    scanReceipt: 'Escanear Recibo',
    useCamera: 'Usar Cámara',
    uploadReceipt: 'Subir Recibo',
    processing: 'Procesando Visión Neuronal...',
    expenseSubmission: 'Envío de Gasto',
    paymentMethod: 'Método de Pago',
    allCategories: 'Todas las Categorías',
    allDepartments: 'Todos los Departamentos',
    filterByDate: 'Filtrar por Fecha',
    addExpense: 'Agregar Nuevo Gasto',
    editExpense: 'Editar Gasto',
    viewReceipt: 'Ver Recibo',
    noReceipt: 'Sin Recibo Adjunto',
    confirmDelete: '¿Está seguro de que desea eliminar esto?',
    rapidNavigation: 'Navegación Rápida',
    goToDashboard: 'Ir al Panel',
    searchMembers: 'Buscar Miembros',
    fiscalPlanning: 'Planificación Fiscal',
    fundAccounting: 'Contabilidad de Fondos',
    trialEnding: 'La prueba termina en',
    days: 'días',
    day: 'día',
    upgradeNow: 'Actualizar Ahora',
    renewsIn: 'La suscripción se renueva en',
    activeTrial: 'Prueba gratuita',
    remaining: 'restantes',
    seePlans: 'Ver Planes',
    loadingWorkspace: 'Cargando su espacio de trabajo...',
    congregation: 'Congregación',
    activeMembers: 'Miembros Activos',
    addMember: 'Agregar Miembro',
    editMember: 'Editar Miembro',
    sendStatement: 'Enviar Estado',
    viewStatement: 'Ver Estado',
    joined: 'Se unió',
    role: 'Rol',
    volunteer: 'Voluntario',
    deacon: 'Diácono',
    financialOverview: 'Resumen Financiero',
    revenueVsExpenses: 'Ingresos vs Gastos',
    newTransaction: 'Nueva Transacción',
    exportPDF: 'Exportar PDF',
    recentTransactions: 'Transacciones Recientes',
    financialHealth: 'Salud Financiera',
    quickAccess: 'Acceso Rápido',
    missionMatrixDesc: 'Progresión de fondos en tiempo real',
    latestLedgerActivity: 'Actividad más reciente del libro mayor',
    keyPerformanceIndicators: 'Indicadores clave de rendimiento',
    budgetUtilization: 'Utilización del Presupuesto',
    withinTarget: 'Dentro del objetivo',
    nearLimit: 'Cerca del límite',
    secureEncrypted: 'Seguro y Encriptado',
    dataProtected: 'Todos los datos protegidos',
    analyticsTitle: 'Analítica Financiera',
    analyticsDesc: 'Métricas YTD/MTD, tendencias de ingresos y desgloses de gastos.',
    memberMgmtTitle: 'Gestión de Miembros',
    memberMgmtDesc: 'Base de datos segura con historial completo de donaciones y conocimientos.',
    expenseWorkflowTitle: 'Flujo de Trabajo de Gastos',
    expenseWorkflowDesc: 'Seguimiento de gastos categorizado con aprobaciones multinivel.',
    smartGivingDesc: 'Donaciones en línea, seguimiento de promesas y analítica de donantes.',
    payrollStaffTitle: 'Nómina y Personal',
    payrollStaffDesc: 'Nómina automatizada con cálculos de impuestos y cumplimiento.',
    budgetPlanningTitle: 'Planificación Presupuestaria',
    budgetPlanningDesc: 'Asignación presupuestaria anual por departamento y fondo.',
    live: 'En vivo',
    thisMonth: 'Este mes',
    unusualPatternsDetected: 'Patrones Inusuales Detectados',
    neuralEngineFlagged: 'Nuestro motor neuronal identificó transacciones que se desvían significativamente de su promedio de 6 meses.',
    strategic: 'Estratégico',
    fiscalManagementDesc: 'Gestión fiscal y planificación de recursos de varios años',
    defineCeiling: 'Defina el techo total para este período fiscal',
    addAllocationLine: 'AGREGAR NUEVA LÍNEA DE ASIGNACIÓN',
    selectDepartment: 'Seleccione un departamento...',
    allocationIntegrity: 'Integridad de la Asignación',
    systemBalanced: 'Sistema Equilibrado',
    imbalance: 'Desequilibrio',
    totalPledgesBudget: 'Presupuesto/Promesas Totales',
    historicalContext: 'Contexto Histórico',
    viewingBudgetFor: 'Viendo el presupuesto para ',
    planningFutureYears: '. La planificación para años futuros permite a la iglesia anticipar el crecimiento.',
    expenseRegistry: 'Registro de Gastos',
    auditableRecordDesc: 'Registro auditable de desembolsos',
    new: 'Nuevo',
    clear: 'Limpiar',
    savePreset: 'Guardar Ajuste',
    outflowTotal: 'Total de Egresos',
    updateExpense: 'Actualizar Gasto',
    newExpense: 'Nuevo Gasto',
    receiptPdf: 'Imagen del Recibo o PDF',
    uploadDoc: 'Subir Doc',
    uploadingSecureDoc: 'Subiendo documento seguro...',
    pdfUploaded: 'PDF subido',
    recordUpdate: 'Registrar Actualización',
    commitToLedger: 'Comprometer al Libro Mayor',
    useCameraApp: 'Usar App de Cámara',
    browseFiles: 'Explorar Archivos',
    extractingLineItems: 'Extrayendo artículos con IA...',
    receiptExtracted: 'Recibo Extraído',
    confirmDetailsDesc: 'Confirme los detalles antes de guardar.',
    churchDepartments: 'Departamentos de la Iglesia',
    departmentsDesc: 'Administre y organice los diversos ministerios y unidades operativas.',
    createDepartment: 'Crear Departamento',
    editDepartment: 'Editar Departamento',
    newDepartment: 'Nuevo Departamento',
    updateDetailsDesc: 'Actualice los detalles de este departamento.',
    initializeMinistryDesc: 'Inicializar un nuevo ministerio o departamento funcional.',
    departmentName: 'NOMBRE DEL DEPARTAMENTO',
    departmentHead: 'JEFE DE DEPARTAMENTO',
    classification: 'CLASIFICACIÓN',
    briefPurposeDesc: 'Propósito breve del departamento...',
    membersVolunteers: 'Miembros / Voluntarios',
    viewRoster: 'Ver Lista',
    communityCore: 'Núcleo de la Comunidad',
    cultivatingEngagementDesc: 'Cultivando el compromiso y fomentando el crecimiento espiritual',
    bulkStatements: 'Declaraciones en Lote',
    membersUsed: 'miembros usados',
    statement: 'Estado de Cuenta',
    editMemberDetails: 'Editar Detalles del Miembro',
    removeMember: 'Eliminar Miembro',
    manuallyAddMemberDesc: 'Agregar manualmente un miembro a la base de datos.',
    churchTreasurer: 'Tesorero de la Iglesia',
    preparedFor: 'PREPARADO PARA',
    totalContributed: 'TOTAL CONTRIBUIDO',
    statementPeriod: 'Período del Estado',
    statementDate: 'Fecha del Estado',
    contributionStatement: 'ESTADO DE CONTRIBUCIONES',
    updateDetailsFor: 'Actualizar detalles para',
    boardReport: 'Informe de la Junta Mensual',
    pnlStatement: 'Estado de Pérdidas y Ganancias',
    balanceSheet: 'Balance General',
    cashflowStatement: 'Estado de Flujo de Caja',
    financialIntelligence: 'Inteligencia Financiera',
    auditReadyDesc: 'Estados financieros listos para auditoría, información para la junta y seguimiento de mayordomía en tiempo real.',
    missionCriticalStatements: 'Declaraciones Críticas de la Misión',
    viewNow: 'Ver Ahora',
    automatedReports: 'Informes Automatizados',
    monthlyFinancialClose: 'Cierre Financiero Mensual',
    nextRun: 'Próxima ejecución',
    activeSchedule: 'Programa Activo',
    manageRecipients: 'Administrar Destinatarios',
    revenueAccuracy: 'Precisión de los Ingresos',
    boardCompliance: 'Cumplimiento de la Junta',
    auditTrail: 'Pista de Auditoría',
    reportLatency: 'Latencia de Informes',
    newAuditRequest: 'Nueva Solicitud de Auditoría',
    statementOfActivity: 'Estado de Actividad',
    operatingPeriod: 'Período Operativo',
    netOperatingIncome: 'Ingresos Operativos Netos',
    revenueSources: 'Fuentes de Ingresos',
    operatingExpenses: 'Gastos Operativos',
    totalExpenditures: 'Gastos Totales',
    statementOfFinancialPosition: 'Estado de Situación Financiera',
    reportingDate: 'Fecha de Informe',
    consolidatedAssets: 'Activos Consolidados',
    cashLiquidEquivalents: 'Efectivo y Equivalentes Líquidos',
    totalPortfolioValue: 'Valor Total de la Cartera',
    netAssetsEquity: 'Activos Netos (Patrimonio)',
    designatedRestrictedFunds: 'Fondos Designados/Restringidos',
    operatingGeneralFunds: 'Fondos Operativos/Generales',
    totalEquity: 'Total Patrimonio',
    assetIntegrityVerified: 'Integridad de Activos Verificada',
    ledgerBalancesMatchDesc: 'Los saldos del libro mayor coinciden con las asignaciones históricas de fondos con precisión.',
    boardPerformanceSummary: 'Resumen de Desempeño de la Junta',
    financialHealthStewardshipOverview: 'Descripción General de Salud Financiera y Mayordomía',
    totalMonthlyRevenue: 'Ingresos Mensuales Totales',
    administrativeOutflow: 'Flujo de Salida Administrativo',
    missionSurplus: 'Superávit de la Misión',
    revenueInflow: 'Flujo de Entrada de Ingresos',
    categorizedStewardshipDesc: 'Mayordomía categorizada por departamento y tipo de fondo',
    operationalOutflow: 'Flujo de Salida Operativo',
    topMonthlyExpenditureDesc: 'Principales categorías de gastos mensuales',
    monthlyTotal: 'TOTAL MENSUAL',
    revenueBySource: 'Ingresos por Fuente',
    expenseAllocation: 'Asignación de Gastos',
    totalDesignatedRevenue: 'Ingresos Designados Totales',
    totalStewardshipBurn: 'Consumo Total de Mayordomía',
    analyzingChurchFinances: 'Analizando Finanzas de la Iglesia...',
    publishToBoard: 'Publicar a la Junta',
    tracingMovementDesc: 'Rastreando el movimiento de activos líquidos a través de ciclos operativos.',
    operatingInflow: 'Flujo de Entrada Operativo',
    operatingOutflow: 'Flujo de Salida Operativo',
    executive: 'Ejecutivo',
    financial: 'Financiero',
    month0: 'Enero',
    month1: 'Febrero',
    month2: 'Marzo',
    month3: 'Abril',
    month4: 'Mayo',
    month5: 'Junio',
    month6: 'Julio',
    month7: 'Agosto',
    month8: 'Septiembre',
    month9: 'Octubre',
    month10: 'Noviembre',
    month11: 'Diciembre',
    // Settings
    systemConfiguration: 'Configuración del Sistema',
    workspaceSettings: 'Ajustes del Espacio de Trabajo',
    manageOrgDetails: 'Administre los detalles principales, facturación y permisos de equipo de su organización.',
    churchIdentity: 'Identidad de la Iglesia',
    churchIdentityDesc: 'Nombre, logo, dirección e información de contacto.',
    financialControls: 'Controles Financieros',
    financialControlsDesc: 'Moneda, año fiscal y configuración de impuestos.',
    billing: 'Planes y Facturación',
    billingDesc: 'Detalles de suscripción y métodos de pago.',
    security: 'Seguridad y Equipo',
    securityDesc: 'Permisos de administrador y autenticación de múltiples factores.',
    appearance: 'Apariencia',
    appearanceDesc: 'Tema, colores de marca y densidad de visualización.',
    notifications: 'Notificaciones',
    notificationsDesc: 'Alertas por correo electrónico para presupuestos y gastos.',
    configure: 'Configurar',
    saveChanges: 'Guardar Cambios',
    backToSettings: 'Volver a Ajustes',
    manageChurchAppearance: 'Administre cómo aparece su iglesia en la plataforma e informes.',
    churchName: 'Nombre de la Iglesia',
    website: 'Sitio Web',
    taxIdEin: 'ID de Impuestos / EIN',
    physicalAddress: 'Dirección Física',
    verifiedStatus: 'Estado Verificado',
    verifiedStatusDesc: 'El perfil de su iglesia está verificado actualmente para recibos que cumplen con los impuestos.',
    adminAccess: 'Acceso Administrativo',
    primaryAdmin: 'Administrador Principal',
    inviteTeamMember: 'Invitar Miembro del Equipo',
    securityProtocols: 'Protocolos de Seguridad',
    mfa: 'Autenticación de Múltiples Factores',
    mfaDesc: 'Requerir 2FA para todos los inicios de sesión de administrador.',
    usageHistory: 'Historial de Uso',
    viewAllInvoices: 'Ver todas las facturas',
    planLimits: 'Límites del Plan',
    themeMode: 'Modo de Tema',
    brandColor: 'Color de Marca',
    displayDensity: 'Densidad de Visualización',
    emailAlerts: 'Alertas de Correo',
    systemAnnouncements: 'Anuncios del Sistema',
    fiscalSettings: 'Configure su moneda, ajustes fiscales y parámetros de cumplimiento tributario.',
    regionalCurrency: 'Región y Moneda',
    baseCurrency: 'Moneda Base',
    fiscalYearStart: 'Inicio del Año Fiscal',
    taxCompliance: 'Cumplimiento Tributario',
    taxExemptStatus: 'Estado de Exención de Impuestos',
    taxExemptDesc: 'Aplicar estatus 501(c)(3) o caritativo a todos los informes financieros.',
    autoTaxReceipts: 'Recibos de Impuestos Automatizados',
    autoTaxReceiptsDesc: 'Envíe documentación fiscal anual a todos los donantes automáticamente.',
    subscriptionExpired: 'Suscripción Expirada',
    trialEndedDesc: 'Su prueba ha terminado. Actualice a un plan de pago para recuperar el acceso total a todas las funciones.',
    currentPlan: 'Plan Actual',
    freeTrialEndsIn: 'La prueba gratuita termina en',
    daysWithDate: 'días',
    subscriptionActiveRenews: 'Suscripción activa — Se renueva el',
    upgradePlan: 'Actualizar Plan',
    connectedDefault: 'Conectado (Predeterminado)',
    viewAllInvoicesArrow: 'Ver todas las facturas →',
    memberLimit: 'Límite de Miembros',
    unlimited: 'Ilimitado',
    membersUsageDesc: 'Actualmente está usando {used} de {total} miembros permitidos.',
    backToBilling: 'Volver a Facturación',
    congratulationsUpgrade: '¡Felicidades! Su iglesia ha sido actualizada con éxito.',
    light: 'Claro',
    dark: 'Oscuro',
    system: 'Sistema',
    compact: 'Compacto',
    spacious: 'Espacioso',
    budgetThresholds: 'Umbrales de Presupuesto',
    budgetThresholdsDesc: 'Notificar cuando un departamento exceda el 80% de su presupuesto mensual.',
    payrollReminders: 'Recordatorios de Nómina',
    payrollRemindersDesc: 'Recibir alertas 2 días antes del procesamiento de nómina programado.',
    securityEvents: 'Eventos de Seguridad',
    securityEventsDesc: 'Alerta por nuevos inicios de sesión de administrador o cambios de permisos.',
    givingReports: 'Informes de Donaciones',
    givingReportsDesc: 'Resumen semanal de diezmos y actividad de donación inteligente.',
    receiveFeatureUpdates: 'Recibir actualizaciones sobre nuevas funciones de la plataforma y mantenimiento.',
    // Payroll
    teamCompensation: 'Compensación del Equipo',
    payrollDesc: 'Gestión automatizada de nómina para el personal de la iglesia y contratistas especializados',
    taxCenter: 'Centro de Impuestos',
    runPayroll: 'Ejecutar Nómina',
    onboardStaff: 'Dar de Alta Personal',
    hireNewStaff: 'Contratar Nuevo Personal',
    hireStaffDesc: 'Agregar un nuevo empleado o contratista a la nómina.',
    fullName: 'Nombre Completo',
    positionRole: 'Rol del Puesto',
    type: 'Tipo',
    salaryRate: 'Salario / Tarifa',
    payFrequency: 'Frecuencia de Pago',
    setRecurring: 'Establecer como Pago Recurrente',
    payrollSuccessful: 'Nómina Exitosa',
    totalDisbursed: 'Monto Total Desembolsado',
    nextPayrollRun: 'Próxima Ejecución de Nómina',
    activeWorkforce: 'Fuerza Laboral Activa',
    actionRequired: 'Acción Requerida',
    staffRegistry: 'Registro de Personal',
    grossSalary: 'Salario Bruto',
    netDisbursement: 'Desembolso Neto',
    financialCompliance: 'Cumplimiento Financiero',
    complianceDesc: 'Manejo seguro de impuestos, presentaciones automatizadas e informes listos para auditoría',
    auditShield: 'Escudo de Auditoría',
    // Fund Accounting
    fundStewardship: 'Mayordomía de Fondos',
    fundStewardshipDesc: 'Visibilidad completa de Diezmos, Ofrendas Restringidas y Misiones Globales',
    reconcileBank: 'Reconciliar Banco',
    recordDeposit: 'Registrar Depósito',
    integratedLedger: 'Libro Mayor Integrado',
    ledgerDesc: 'Vista unificada de todas las actividades de departamentos y fondos',
    bankReconHub: 'Centro de Reconciliación Bancaria',
    bankStatementItems: 'Artículos del Estado de Cuenta',
    ledgerRecommendations: 'Recomendaciones del Libro Mayor',
    plansPricing: 'Planes y Precios',
    departments: 'Departamentos',
    allocationDetails: 'Detalles de Asignación',
    destinationFund: 'Fondo de Destino',
    bankReconDesc: 'Asociación automática de transacciones de la cuenta operativa Chase (...4920)',
    refreshFeed: 'Actualizar Feed',
    processMatches: 'Procesar Todas las Coincidencias',
    suggestedMatch: 'Coincidencia Sugerida Encontrada',
    exactMatchDesc: 'La entrada "{desc}" con fecha {date} coincide exactamente.',
    confirmMatch: 'Confirmar Coincidencia',
    noDirectMatch: 'No hay coincidencias directas para {desc}.',
    createLedgerLink: 'Crear Enlace al Libro Mayor',
    accountStatus: 'Estado de la Cuenta',
    contributor: 'Contribuyente',
    typeToSearch: 'Escriba para buscar miembro...',
    departmentAllocations: 'Asignaciones de Departamento',
    closeAuditView: 'Cerrar Vista de Auditoría',
    history: 'Historial',
    autoMatchedLedger: 'Autocoincidencia con el Libro Mayor',
    // Fund Names/Types
    generalFundTithes: 'Fondo General (Diezmos)',
    buildingCampaign: 'Campaña de Construcción',
    missionsOutreach: 'Misiones y Alcance',
    youthMinistry: 'Ministerio Juvenil',
    operational: 'Operativo',
    restricted: 'Restringido',
    purpose: 'Propósito',
    active: 'Activo',
    low: 'Bajo',
    healthy: 'Saludable',
    // New Payroll Keys
    amShift: 'Turno AM',
    pmShift: 'Turno PM',
    tMinus8Days: 'Faltan 8 días',
    estDisbursement: 'Desembolso Est.',
    allCompliant: 'Todo en regla',
    pendingApproval: 'Pendiente de aprobación',
    invoiceVerificationNeeded: 'Se requiere verificación de factura',
    staffRegistryDesc: 'Gestión centralizada de la estructura y compensación del equipo',
    searchDirectory: 'Buscar en el directorio...',
    exportData: 'Exportar Datos',
    morning: 'Mañana',
    evening: 'Tarde',
    shift: 'Turno',
    today: 'Hoy',
    contractors: 'contratistas',
    done: 'Hecho',
    payroll: 'Nómina',
    logout: 'Cerrar Sesión',
    notes: 'Notas',
    weighted: 'ponderado',
    statementDear: 'Estimado/a',
    statementGratitude: 'Esperamos que este mensaje le encuentre bien. En nombre de {churchName}, nos gustaría expresar nuestra sincera gratitud por su continuo apoyo y fiel mayordomía.',
    statementAttached: 'Adjunto o detallado a continuación se encuentra su estado de contribución financiera para {month} {year}.',
    statementTotalContribution: 'Contribución Mensual Total',
    statementTransactionRecord: 'REGISTRO DE TRANSACCIONES',
    statementQuestions: 'Sus contribuciones nos permiten continuar el trabajo del ministerio y servir a nuestra comunidad de manera efectiva. Si tiene alguna pregunta con respecto a este estado de cuenta, no dude en ponerse en contacto con la oficina de finanzas.',
    statementBlessings: 'Bendiciones',
    statementTreasurerLabel: 'Tesorero/a',
    statementOfficialReceipt: 'Este estado de cuenta sirve como recibo oficial de sus contribuciones a {churchName} durante el período de {month} {year}. Su fiel apoyo fortalece nuestros ministerios e iniciativas comunitarias. Le agradecemos por su continua colaboración en nuestra misión.',
    statementOfficialSubject: 'Estado de Contribución Oficial',
    dateLabel: 'Fecha',
    fundAllocation: 'Asignación de Fondos',
    churchMessage: 'Un mensaje de su iglesia',
    stewardshipMessage: 'Estimado/a {name}, gracias por su fiel mayordomía este mes. Su contribución de {amount} nos ayuda a continuar nuestra misión de brindar alimento espiritual y alcance comunitario. Su generosidad fortalece nuestros ministerios y transforma vidas a través de la fe.',
    financeTeam: 'Equipo de Finanzas',
    stewardshipCertification: 'Certificación Oficial de Mayordomía',
    donorInformation: 'Información del Donante',
    memberSince: 'Miembro desde',
    transactionDetails: 'Detalles de la Transacción',
    noDonationsRecorded: 'No se registraron donaciones para este período.',
    treasurerSignatureName: 'Nombre de firma del tesorero',
    print: 'Imprimir',
    sendToMember: 'Enviar al Miembro',
    emailSent: '¡Correo Enviado!',
    operatingExp: 'Gasto Operativo',
    restrictedExp: 'Gasto Restringido',
    purposeExp: 'Gasto para Propósito',
    buildingFacilities: 'Edificios e Instalaciones',
    tithesFinance: 'Diezmos y Finanzas',
    sabbathSchool: 'Escuela Sabática',
    sundaySchool: 'Escuela Dominical',
    cash: 'Efectivo',
    check: 'Cheque',
    online: 'En Línea',
    mobileApp: 'App Móvil',
    optionalNotesLabel: 'Notas opcionales sobre esta transacción',
    recordedManually: 'Registrado manualmente vía portal de Mayordomía. Método: {method}',
    importedGateway: 'Imported de Pasarela en Línea',
    seniorPastor: 'Pastor Principal',
    worshipDirector: 'Director de Alabanza',
    youthPastor: 'Pastor de Jóvenes',
    cleaner: 'Personal de Limpieza',
    itSupport: 'Soporte IT',
    securityDetail: 'Seguridad',
    fullTime: 'Tiempo completo',
    contractor: 'Contratista',
    paid: 'Pagado',
    pending: 'Pendiente',
    monthly: 'Mensual',
    twiceDaily: 'Dos veces al día',
    'Senior Pastor': 'Pastor Principal',
    'Worship Director': 'Director de Alabanza',
    'Youth Pastor': 'Pastor de Jóvenes',
    'Cleaner': 'Personal de Limpieza',
    'IT Support': 'Soporte IT',
    'Security Detail': 'Seguridad',
    'Full-time': 'Tiempo completo',
    'Part-time': 'Tiempo parcial',
    'Contractor': 'Contratista',
    'Paid': 'Pagado',
    'Pending': 'Pendiente',
    'Monthly': 'Mensual',
    'Twice Daily': 'Dos veces al día',
    'Weekly': 'Semanales',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string) => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
