import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { HelpCircle, Mail, Book, X, Send, Sparkles, ChevronDown, MessageSquare } from 'lucide-react';

interface SupportModalProps {
    isOpen: boolean;
    onClose: () => void;
}

const FAQ_DATA = [
    {
        category: "Billing & Subscriptions",
        questions: [
            {
                q: "Why did my PayPal payment fail?",
                a: "Ensure your card is not expired and has sufficient funds. PayPal sometimes blocks transactions if it suspects unusual activity; try clearing your cache or using a different card."
            },
            {
                q: "How do I upgrade my plan?",
                a: "You can upgrade at any time by clicking 'Upgrade' in the sidebar or going to Settings > Church Identity. Your new member limits will apply immediately."
            },
            {
                q: "Is the 30-day trial fully featured?",
                a: "Yes! You get access to all features during the trial. However, there is a hard cap of 15 members during the trial period."
            }
        ]
    },
    {
        category: "Team & Member Management",
        questions: [
            {
                q: "I invited a team member but they can't see our church data.",
                a: "Ensure they created their account using the exact same email address that you sent the invitation to. If they used a different email, they will not be linked to your church."
            },
            {
                q: "How do I remove a team member?",
                a: "Go to Settings > Team Management. Click the 'Remove' button next to their name. They will immediately lose access to all financial data."
            }
        ]
    },
    {
        category: "Reports & Tax Compliance",
        questions: [
            {
                q: "Why is my dashboard chart empty?",
                a: "Charts calculate data based on your Fiscal Year settings and recorded transactions. Ensure you have actual transactions logged for the current active fiscal year."
            },
            {
                q: "How do I change our Fiscal Year start month?",
                a: "Go to Settings > Church Identity. You can select your starting month from the dropdown. All reports will instantly adapt to this schedule."
            },
            {
                q: "Are the generated Tax PDFs official IRS forms?",
                a: "No. The PDFs generated by Storehouse Finance are worksheets designed to help you easily prepare your official filings. Always submit final forms directly to the IRS or consult a tax professional."
            }
        ]
    }
];

const SupportModal: React.FC<SupportModalProps> = ({ isOpen, onClose }) => {
    const [view, setView] = useState<'contact' | 'knowledge'>('knowledge');
    const [message, setMessage] = useState('');
    const [sending, setSending] = useState(false);
    const [success, setSuccess] = useState(false);
    
    // Track expanded FAQ (null if none, string if category-index)
    const [expandedFaq, setExpandedFaq] = useState<string | null>(null);

    if (!isOpen) return null;

    const handleSend = async (e: React.FormEvent) => {
        e.preventDefault();
        setSending(true);
        // Simulate sending
        await new Promise(r => setTimeout(r, 1500));
        setSending(false);
        setSuccess(true);
        setTimeout(() => {
            setSuccess(false);
            setMessage('');
            onClose();
        }, 2000);
    };

    return (
        <AnimatePresence>
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                style={{
                    position: 'fixed', inset: 0, zIndex: 9999,
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    background: 'rgba(2,6,23,0.85)', backdropFilter: 'blur(12px)',
                    padding: '1.5rem',
                }}
            >
                <motion.div
                    initial={{ scale: 0.95, y: 30 }}
                    animate={{ scale: 1, y: 0 }}
                    exit={{ scale: 0.95, y: 30 }}
                    style={{
                        width: '100%', maxWidth: '540px', background: '#0f172a',
                        border: '1px solid rgba(255,255,255,0.08)', borderRadius: '24px',
                        boxShadow: '0 25px 60px -12px rgba(0,0,0,0.5)',
                        position: 'relative', overflow: 'hidden',
                        maxHeight: '90vh', display: 'flex', flexDirection: 'column'
                    }}
                >
                    {/* Visual Header Decoration */}
                    <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: '4px', background: 'linear-gradient(90deg, #2563eb, #8b5cf6, #2563eb)' }} />
                    
                    <div style={{ padding: '2rem 2rem 1rem', flexShrink: 0 }}>
                        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: '1.5rem' }}>
                            <div style={{
                                width: '56px', height: '56px', borderRadius: '16px',
                                background: 'rgba(37,99,235,0.1)', border: '1px solid rgba(37,99,235,0.2)',
                                display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#60a5fa'
                            }}>
                                <HelpCircle size={28} />
                            </div>
                            <button onClick={onClose} style={{ padding: '8px', borderRadius: '10px', background: 'none', border: 'none', color: '#475569', cursor: 'pointer' }}>
                                <X size={20} />
                            </button>
                        </div>

                        <h2 style={{ fontSize: '1.5rem', fontWeight: 900, color: 'white', marginBottom: '0.5rem', letterSpacing: '-0.02em' }}>
                            Support & Resources
                        </h2>
                        
                        <div style={{ display: 'flex', gap: '0.5rem', background: 'rgba(255,255,255,0.03)', padding: '0.25rem', borderRadius: '12px', marginTop: '1.5rem' }}>
                            <button
                                onClick={() => setView('knowledge')}
                                style={{
                                    flex: 1, padding: '0.75rem', borderRadius: '10px', border: 'none',
                                    background: view === 'knowledge' ? 'rgba(255,255,255,0.1)' : 'transparent',
                                    color: view === 'knowledge' ? 'white' : '#64748b',
                                    fontWeight: 700, fontSize: '0.85rem', cursor: 'pointer', transition: 'all 0.2s',
                                    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem'
                                }}
                            >
                                <Book size={16} /> Knowledge Base
                            </button>
                            <button
                                onClick={() => setView('contact')}
                                style={{
                                    flex: 1, padding: '0.75rem', borderRadius: '10px', border: 'none',
                                    background: view === 'contact' ? 'rgba(255,255,255,0.1)' : 'transparent',
                                    color: view === 'contact' ? 'white' : '#64748b',
                                    fontWeight: 700, fontSize: '0.85rem', cursor: 'pointer', transition: 'all 0.2s',
                                    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem'
                                }}
                            >
                                <MessageSquare size={16} /> Contact Us
                            </button>
                        </div>
                    </div>

                    <div style={{ padding: '0 2rem 2rem', overflowY: 'auto', flex: 1 }}>
                        <AnimatePresence mode="wait">
                            {view === 'knowledge' ? (
                                <motion.div
                                    key="knowledge"
                                    initial={{ opacity: 0, x: -10 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    exit={{ opacity: 0, x: 10 }}
                                    transition={{ duration: 0.2 }}
                                >
                                    <p style={{ fontSize: '0.85rem', color: '#94a3b8', marginBottom: '1.5rem', lineHeight: '1.6' }}>
                                        Find immediate answers to common technical questions and troubleshoot issues without waiting for a response.
                                    </p>
                                    
                                    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
                                        {FAQ_DATA.map((section, sIndex) => (
                                            <div key={sIndex}>
                                                <h3 style={{ fontSize: '0.75rem', fontWeight: 800, color: '#60a5fa', textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: '0.75rem' }}>
                                                    {section.category}
                                                </h3>
                                                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                                                    {section.questions.map((faq, qIndex) => {
                                                        const id = `${sIndex}-${qIndex}`;
                                                        const isExpanded = expandedFaq === id;
                                                        return (
                                                            <div 
                                                                key={qIndex} 
                                                                style={{ 
                                                                    background: isExpanded ? 'rgba(255,255,255,0.06)' : 'rgba(255,255,255,0.02)', 
                                                                    border: `1px solid ${isExpanded ? 'rgba(255,255,255,0.1)' : 'rgba(255,255,255,0.04)'}`, 
                                                                    borderRadius: '12px', overflow: 'hidden', transition: 'all 0.2s'
                                                                }}
                                                            >
                                                                <button
                                                                    onClick={() => setExpandedFaq(isExpanded ? null : id)}
                                                                    style={{ 
                                                                        width: '100%', padding: '1rem', background: 'none', border: 'none', 
                                                                        display: 'flex', alignItems: 'center', justifyContent: 'space-between', 
                                                                        cursor: 'pointer', textAlign: 'left', color: isExpanded ? 'white' : '#cbd5e1'
                                                                    }}
                                                                >
                                                                    <span style={{ fontSize: '0.85rem', fontWeight: 600, paddingRight: '1rem' }}>{faq.q}</span>
                                                                    <ChevronDown size={16} style={{ transform: isExpanded ? 'rotate(180deg)' : 'none', transition: 'transform 0.2s', flexShrink: 0, color: '#64748b' }} />
                                                                </button>
                                                                
                                                                <AnimatePresence>
                                                                    {isExpanded && (
                                                                        <motion.div
                                                                            initial={{ height: 0, opacity: 0 }}
                                                                            animate={{ height: 'auto', opacity: 1 }}
                                                                            exit={{ height: 0, opacity: 0 }}
                                                                            transition={{ duration: 0.2 }}
                                                                        >
                                                                            <div style={{ padding: '0 1rem 1rem', fontSize: '0.8rem', color: '#94a3b8', lineHeight: '1.6' }}>
                                                                                {faq.a}
                                                                            </div>
                                                                        </motion.div>
                                                                    )}
                                                                </AnimatePresence>
                                                            </div>
                                                        );
                                                    })}
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                </motion.div>
                            ) : (
                                <motion.div
                                    key="contact"
                                    initial={{ opacity: 0, x: 10 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    exit={{ opacity: 0, x: -10 }}
                                    transition={{ duration: 0.2 }}
                                >
                                    <p style={{ fontSize: '0.85rem', color: '#94a3b8', marginBottom: '1.5rem', lineHeight: '1.6' }}>
                                        Couldn't find what you need in the Knowledge Base? Send our support team a message.
                                    </p>
                                    
                                    {!success ? (
                                        <form onSubmit={handleSend} style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
                                            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                                                <label style={{ fontSize: '0.75rem', fontWeight: 700, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.07em' }}>
                                                    How can we help?
                                                </label>
                                                <textarea 
                                                    value={message}
                                                    onChange={e => setMessage(e.target.value)}
                                                    placeholder="Describe the challenge or question you have..."
                                                    required
                                                    style={{
                                                        width: '100%', minHeight: '120px', padding: '1rem',
                                                        borderRadius: '12px', background: 'rgba(255,255,255,0.04)',
                                                        border: '1px solid rgba(255,255,255,0.08)', color: 'white',
                                                        fontSize: '0.95rem', outline: 'none', transition: 'all 0.2s', resize: 'none'
                                                    }}
                                                    onFocus={e => (e.target.style.borderColor = '#2563eb')}
                                                    onBlur={e => (e.target.style.borderColor = 'rgba(255,255,255,0.08)')}
                                                />
                                            </div>

                                            <button
                                                type="submit"
                                                disabled={sending}
                                                style={{
                                                    padding: '1rem', borderRadius: '12px', border: 'none',
                                                    background: 'linear-gradient(135deg, #2563eb, #1d4ed8)', color: 'white',
                                                    fontWeight: 800, fontSize: '0.95rem', cursor: 'pointer',
                                                    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.75rem',
                                                    opacity: sending ? 0.7 : 1, transition: 'all 0.3s',
                                                    boxShadow: '0 8px 20px -6px rgba(37,99,235,0.4)',
                                                }}
                                            >
                                                {sending ? 'Sending...' : (
                                                    <>
                                                        Submit Request <Send size={18} />
                                                    </>
                                                )}
                                            </button>

                                            <div style={{ display: 'flex', justifyContent: 'center', marginTop: '0.5rem' }}>
                                                <div style={{ padding: '1rem', borderRadius: '12px', background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.04)', textAlign: 'center', width: '100%' }}>
                                                    <Mail size={16} color="#60a5fa" style={{ marginBottom: '8px' }} />
                                                    <div style={{ fontSize: '0.7rem', fontWeight: 800, color: '#94a3b8', textTransform: 'uppercase' }}>Direct Email</div>
                                                    <div style={{ fontSize: '0.8rem', color: 'white', marginTop: '4px' }}>support@storehousefinance.net</div>
                                                </div>
                                            </div>
                                        </form>
                                    ) : (
                                        <motion.div
                                            initial={{ opacity: 0, scale: 0.95 }}
                                            animate={{ opacity: 1, scale: 1 }}
                                            style={{ textAlign: 'center', padding: '3rem 0' }}
                                        >
                                            <div style={{
                                                width: '64px', height: '64px', borderRadius: '50%',
                                                background: 'rgba(16,185,129,0.1)', border: '2px solid rgba(16,185,129,0.2)',
                                                display: 'flex', alignItems: 'center', justifyContent: 'center',
                                                margin: '0 auto 1.5rem', color: '#10b981'
                                            }}>
                                                <Sparkles size={32} />
                                            </div>
                                            <h3 style={{ color: 'white', fontSize: '1.25rem', fontWeight: 800, marginBottom: '0.5rem' }}>Request Received</h3>
                                            <p style={{ color: '#64748b', fontSize: '0.9rem', fontWeight: 500 }}>Our stewards will review your request and get back to you within 24 hours.</p>
                                        </motion.div>
                                    )}
                                </motion.div>
                            )}
                        </AnimatePresence>
                    </div>
                </motion.div>
            </motion.div>
        </AnimatePresence>
    );
};

export default SupportModal;
